int pgmraw_to_fits (char *pgmfile, char *fitsfile)

{FITS_FILE *fitsout = NULL;
 FILE *pgmin = NULL;
 FITS_HDU_LIST *hdu;
 char buffer[1024];
 int width, height, numbytes, maxbytes;
 int retval = -1;

 fitsout = fits_open (fitsfile, "w");
 if (fitsout == NULL) goto err_return;

 pgmin = g_fopen (pgmfile, "r");
 if (pgmin == NULL) goto err_return;

 /* Read signature of PGM file */
 if (fgets (buffer, sizeof (buffer), pgmin) == NULL) goto err_return;
 if ((buffer[0] != 'P') || (buffer[1] != '5')) goto err_return;

 /* Skip comments upto width/height */
 do
 {
   if (fgets (buffer, sizeof (buffer), pgmin) == NULL) goto err_return;
 } while (buffer[0] == '#');

 if (sscanf (buffer, "%d%d", &width, &height) != 2) goto err_return;
 if ((width < 1) || (height < 1)) goto err_return;

 /* Skip comments upto maxval */
 do
 {
   if (fgets (buffer, sizeof (buffer), pgmin) == NULL) goto err_return;
 } while (buffer[0] == '#');
 /* Ignore maxval */

 hdu = fits_add_hdu (fitsout);     /* Create a HDU for the FITS file */
 if (hdu == NULL) goto err_return;

 hdu->used.simple = 1;         /* Set proper values */
 hdu->bitpix = 8;
 hdu->naxis = 2;
 hdu->naxisn[0] = width;
 hdu->naxisn[1] = height;
 hdu->used.datamin = 1;
 hdu->datamin = 0.0;
 hdu->used.datamax = 1;
 hdu->datamax = 255.0;
 hdu->used.bzero = 1;
 hdu->bzero = 0.0;
 hdu->used.bscale = 1;
 hdu->bscale = 1.0;

 fits_add_card (hdu, "");
 fits_add_card (hdu, "HISTORY THIS FITS FILE WAS GENERATED BY FITSRW\
 USING PGMRAW_TO_FITS");

 /* Write the header. Blocking is done automatically */
 if (fits_write_header (fitsout, hdu) < 0) goto err_return;

 /* The primary array plus blocking must be written manually */
 numbytes = width * height;

 while (numbytes > 0)
 {
   maxbytes = sizeof (buffer);
   if (maxbytes > numbytes) maxbytes = numbytes;

   if (fread (buffer, 1, maxbytes, pgmin) != maxbytes) goto err_return;
   if (fwrite (buffer, 1, maxbytes, fitsout->fp) != maxbytes) goto err_return;

   numbytes -= maxbytes;
 }

 /* Do blocking */
 numbytes = (width * height) % FITS_RECORD_SIZE;
 if (numbytes)
 {
   while (numbytes++ < FITS_RECORD_SIZE)
     if (putc (0, fitsout->fp) == EOF) goto err_return;
 }
 retval = 0;

err_return:

 if (fitsout) fits_close (fitsout);
 if (pgmin) fclose (pgmin);

 return (retval);
}